### ISSUE TITLE
Abort recovery

### ISSUE THREAD

**Issue by jleibund** [wglass/zoonado#22]
I noticed this issue during  loss of connectivity to zookeeper in the heartbeat/abort recovery code.  In the following trace I have run the locking example and, while running, I stopped zookeeper.  The abort procedure never completes due to what looks like the wrong expectation of what is in self.pending_specials:

```
(devenv) jpleibundguth@ubuntu:~/ltest/localcontroller/repos/zoonado$ ./examples/run locking
INFO:root:Launching 3 workers.
INFO:zoonado.session:Connecting to localhost:2181
INFO:zoonado.session:Establising session.
INFO:zoonado.session:Got session id 0x15ba5270b370000
INFO:zoonado.session:Negotiated timeout: 10 seconds
INFO:root:[WORKER #2] Acquiring lock...
INFO:root:[WORKER #1] Acquiring lock...
INFO:root:[WORKER #0] Acquiring lock...
INFO:root:[WORKER #2] Got lock!
INFO:root:[WORKER #2] working 3 secs
INFO:root:[WORKER #2] working 3 secs
INFO:root:[WORKER #2] working 2 secs
INFO:root:[WORKER #2] Done!
INFO:root:[WORKER #1] Got lock!
INFO:root:[WORKER #1] working 1 secs
INFO:root:[WORKER #1] working 1 secs
INFO:root:[WORKER #1] working 3 secs
INFO:root:[WORKER #1] Done!
INFO:root:[WORKER #0] Got lock!
INFO:root:[WORKER #0] working 3 secs
INFO:root:[WORKER #0] working 3 secs
WARNING:zoonado.connection:Aborting connection to localhost:2181
INFO:root:[WORKER #0] working 1 secs
ERROR:tornado.application:Exception in callback <functools.partial object at 0x7fd3f3e77b50>
Traceback (most recent call last):
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/ioloop.py", line 604, in _run_callback
    ret = callback()
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/ioloop.py", line 619, in <lambda>
    self.add_future(ret, lambda f: f.result())
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/zoonado/session.py", line 211, in heartbeat
    zxid, _ = yield self.conn.send(protocol.PingRequest())
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/zoonado/connection.py", line 127, in send
    self.abort()
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/zoonado/connection.py", line 214, in abort
    for pending in self.drain_all_pending():
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/zoonado/connection.py", line 219, in drain_all_pending
    for _, f in iterables.drain(self.pending_specials[special_xid]):
TypeError: 'Future' object is not iterable
INFO:root:[WORKER #0] Done!
WARNING:zoonado.connection:Aborting connection to localhost:2181
WARNING:zoonado.connection:Aborting connection to localhost:2181
ERROR:tornado.application:Exception in callback <functools.partial object at 0x7fd3f3e3de68>
Traceback (most recent call last):
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/ioloop.py", line 604, in _run_callback
    ret = callback()
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/ioloop.py", line 619, in <lambda>
    self.add_future(ret, lambda f: f.result())
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/zoonado/recipes/base_lock.py", line 72, in on_exit
    yield self.delete_unique_znode(znode_label)
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/zoonado/recipes/sequential.py", line 54, in delete_unique_znode
    yield self.client.delete(self.owned_paths[znode_label])
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/zoonado/client.py", line 194, in delete
    yield self.send(protocol.DeleteRequest(path=path, version=version))
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/zoonado/client.py", line 95, in send
    response = yield self.session.send(request)
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/zoonado/session.py", line 184, in send
    zxid, response = yield self.conn.send(request, xid=self.xid)
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/zoonado/connection.py", line 125, in send
    self.stream.write(payload).add_done_callback(handle_write)
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/iostream.py", line 377, in write
    self._check_closed()
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/iostream.py", line 885, in _check_closed
    raise StreamClosedError(real_error=self.error)
StreamClosedError: Stream is closed
ERROR:tornado.application:Exception in callback <functools.partial object at 0x7fd3f3e3dec0>
Traceback (most recent call last):
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/ioloop.py", line 604, in _run_callback
    ret = callback()
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "./examples/run", line 93, in wind_down
    f.result()
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/examples/locking.py", line 32, in run
    yield client.close()
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/zoonado/client.py", line 106, in close
    yield self.session.close()
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/zoonado/session.py", line 277, in close
    yield self.send(protocol.CloseRequest())
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/zoonado/session.py", line 184, in send
    zxid, response = yield self.conn.send(request, xid=self.xid)
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/zoonado/connection.py", line 125, in send
    self.stream.write(payload).add_done_callback(handle_write)
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/iostream.py", line 377, in write
    self._check_closed()
  File "/home/jpleibundguth/ltest/localcontroller/devenv/local/lib/python2.7/site-packages/tornado/iostream.py", line 885, in _check_closed
    raise StreamClosedError(real_error=self.error)
StreamClosedError: Stream is closed
```

**Comment by wglass** [comment]
Fixed by #23
