### ISSUE TITLE
Not compatible with python 3.5?

### ISSUE THREAD

**Issue by Soniccube** [wglass/zoonado#3]
I am trying to use zoonado with python 3.5 and tornado 4.4, but I found it has many problems with string encoding? It seems that this client is not compatible with python 3+?

**Comment by wglass** [comment]
I support python 3.5 and have made sure the tests run under python 3.5, but there are some important parts that haven't been covered yet.

It's likely I goofed up some encoding/decoding somewhere without realizing it.

Do you have any stacktraces of the errors you saw?  I'd be happy to fix them once I know where to look.

**Comment by cybergrind** [comment]
I have issues when running it on python 3.5. It fails from very beginning

```
ERROR:zoonado.session:Couldn't connect to localhost:2181
Traceback (most recent call last):
  File "/home/kpi/tmp/zoonado/venv/lib/python3.5/site-packages/zoonado/session.py", line 104, in make_connection
    yield conn.connect()
  File "/home/kpi/tmp/zoonado/venv/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/home/kpi/tmp/zoonado/venv/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/kpi/tmp/zoonado/venv/lib/python3.5/site-packages/tornado/gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "/home/kpi/tmp/zoonado/venv/lib/python3.5/site-packages/zoonado/connection.py", line 54, in connect
    yield stream.write("srvr")
  File "/home/kpi/tmp/zoonado/venv/lib/python3.5/site-packages/tornado/iostream.py", line 376, in write
    assert isinstance(data, bytes)
AssertionError
WARNING:zoonado.session:No servers available, will keep trying.
```

I was able to fix that with couple of changes, like:

```python
    @gen.coroutine
    def connect(self):
        client = tcpclient.TCPClient()

        log.debug("Initial connection to server %s:%d", self.host, self.port)
        stream = yield client.connect(self.host, self.port)

        log.debug("Sending 'srvr' command to %s:%d", self.host, self.port)
        yield stream.write(b"srvr")                                                  # <== HERE
        answer = yield stream.read_until_close()

        version_line = answer.split(b"\n")[0].decode('utf8')           # <== HERE
        self.version_info = tuple(
            map(int, version_regex.match(version_line).groups())
        )
        self.start_read_only = bool(b"READ_ONLY" in answer)  # <=== HERE

        log.debug("Version info: %s", self.version_info)
        log.debug("Read-only mode: %s", self.start_read_only)

        log.warn("Actual connection to server %s:%d", self.host, self.port)
        self.stream = yield client.connect(self.host, self.port)
```
But in general I'm feeling that something totally wrong here with bytestring support or with my understanding of problem

Code I've used is very basic, like:

```python
from tornado import gen, ioloop
from zoonado import Zoonado

@gen.coroutine
def run():
    zk = Zoonado("localhost")
    yield zk.start()
    yield zk.create("/foo/bar", data="bazz", ephemeral=True)
    yield zk.set_data("/foo/bar", "bwee")
    yield zk.close()


loop = ioloop.IOLoop.instance()

def cb(f):
    try:
        f.result()
    finally:
        loop.stop()

loop.add_future(run(), cb)
loop.start()
```
After I got:

```
  File "/home/kpi/tmp/zoonado/tz.py", line 9, in run
    yield zk.create("/foo/bar", data="bazz", ephemeral=True)
  File "/home/kpi/devel/tipsi/fan/venv/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/home/kpi/devel/tipsi/fan/venv/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/kpi/devel/tipsi/fan/venv/lib/python3.5/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/kpi/devel/tipsi/fan/venv/lib/python3.5/site-packages/zoonado/client.py", line 130, in create
    response = yield self.send(request)
  File "/home/kpi/devel/tipsi/fan/venv/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/home/kpi/devel/tipsi/fan/venv/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/kpi/devel/tipsi/fan/venv/lib/python3.5/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/kpi/devel/tipsi/fan/venv/lib/python3.5/site-packages/zoonado/client.py", line 75, in send
    response = yield self.session.send(request)
  File "/home/kpi/devel/tipsi/fan/venv/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/home/kpi/devel/tipsi/fan/venv/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/kpi/devel/tipsi/fan/venv/lib/python3.5/site-packages/tornado/gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "/home/kpi/devel/tipsi/fan/venv/lib/python3.5/site-packages/zoonado/session.py", line 178, in send
    zxid, response = yield self.conn.send(request, xid=self.xid)
  File "/home/kpi/devel/tipsi/fan/venv/lib/python3.5/site-packages/zoonado/connection.py", line 104, in send
    payload = request.serialize(xid)
  File "/home/kpi/devel/tipsi/fan/venv/lib/python3.5/site-packages/zoonado/protocol/request.py", line 38, in serialize
    payload_format, payload_data = self.render()
  File "/home/kpi/devel/tipsi/fan/venv/lib/python3.5/site-packages/zoonado/protocol/part.py", line 45, in render
    part_format, part_data = part.render()
  File "/home/kpi/devel/tipsi/fan/venv/lib/python3.5/site-packages/zoonado/protocol/primitives.py", line 82, in render
    value = self.render_value(self.value)
  File "/home/kpi/devel/tipsi/fan/venv/lib/python3.5/site-packages/zoonado/protocol/primitives.py", line 179, in render_value
    return bytes(value)
TypeError: string argument without an encoding
```

**Comment by wglass** [comment]
Man that's great feedback!  Definitely a bug on my end.

Should be able to take care of it today or this weekend at the latest and cut a patch release.

**Comment by cybergrind** [comment]
Hey, I can't wait too long so decided to hard fork your repo and rewrite some parts to support our requirements. It's pushed here https://github.com/tipsi/aiozk
I've done rewriting basic client features to work with asyncio and python 3.5, also drop python 2.7-3.4 support at all (async/await's are cool).
Recipes/tests are still in progress, but all basic things are work perfectly with asyncio, so thank you a lot!
